version: 2
sources:
  - name: gz_raw_data
    schema: gz_raw_data
    tables:
      - name: raw_sales
        identifier: raw_sales
      - name: raw_product
        identifier: raw_product
      - name: raw_ship
        identifier: raw_ship
      - name: raw_gz_adwords
        identifier: gz_adwords
      - name: raw_gz_bing
        identifier: gz_bing
      - name: raw_gz_criteo
        identifier: gz_criteo
      - name: raw_gz_facebook
        identifier: gz_facebook
        
